_official-repo: &official-repo
  DanySK/Template-IEEE-Computer-Society-Magazines
_github_api_key: &github_api_key
  secure: Hhgw0GUY1z9CIzRV2g2IPqu/m1Eh5i+Xmov1RY7O9JnPPYnX4ziQ5el46FAQ2hZT3r77hK7GlJGRGMuuD3xK1SlJtjvyb/EXLE9T6ChVSPEMRBVPm/tpJgM9Cq7dR9ES60YFDtcD70zW/qvrcTcRiM53NgKnD+SJGI9JCMzq6QMXrDmPxV+iV7vgxDdFDlb7YMO1Aq4x+R64obJY6m3VbJeuC458maUwCs92pz7A/wpAjNYB8OATo05DVwSYse364JOhiQrzo4JUq0VdGugVOiJELiRDrSGSoXGDOa/jebmbUEDOEt2+FncEsJL5Qn8UfKTONrt30/qRTFkxaZrZcY7kPXy4nvYDIk3DT8d7nOq627tcFr1lbezvhOm2HOT15ENj5SoU88S4yudmJKsaDd9znZOIcGRhEiO6NAmK5HU3Do5EAkmmMnlSBKjRJpniQNs3CQXW+yDC4Flvr0I6Mr2leT6QAZlvawMBrgBJ6Sl1ItPv3sViE918PG2/1uIWmiFkCwf+5f6Dy5B8K0sPEZRBzRZA9IMMk2n/QDKuD/qqypraAlBHjdWmZjeRHE/EPVThOEwlr6DhIWuciviO+T2HX6ksoYMHdZo1glgx8jbG4ioUT45fcvZiUoJIl/DOt99jfKtjt2mfgJJaU9vwBesiBo96fkCPHFx7Nv97L1U=

language: java

addons:
  apt:
    update: true
    packages:
      # LaTeX decent font processor
      - cm-super
      # For Minted
      - python-pygments
      # LaTeX
      - texlive-base
      - texlive-extra-utils
      - texlive-generic-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-science
      # Debug
      - tree
      # For git latexdiff
      - latexdiff
      # Image processing
      - inkscape

env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS

install: true

script: ./gradlew buildLatex

before_deploy:
  - git config --local user.name "Danilo Pianini"
  - git config --local user.email "danilo.pianini@unibo.it"
  - if [[ $(git describe) == *"-"* ]]; then git tag $(git describe) || :; fi

before_cache:
  - $GRAVIS/clean-gradle-cache

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  - provider: releases
    api_key: *github_api_key
    file_glob: true
    file: "*.pdf"
    skip_cleanup: true
    on:
      repo: *official-repo
      tags: true
  - provider: releases
    api_key: *github_api_key
    file_glob: true
    file: "*.pdf"
    skip_cleanup: true
    on:
      repo: *official-repo
      tags: false

notifications:
  email:
    on_success: never
